JWT authentication
ebosetalee/shopify-images pull request #2
Opened 2021-06-02 09:38 UTC by ebosetalee

Here are the changes @imadu

2021-06-02 09:52 UTC, imadu requested changes

2021-06-02 09:52 UTC, imadu commented on .env
> +JWT="our_crypto_secret234"
You're not supposed to commit your env files. That's where all our secret stuff goes into. You should add it to your git ignore

2021-06-02 09:52 UTC, imadu commented on controllers/login.js
> +        } else {
Remove the else block, we don't need it .

2021-06-02 09:52 UTC, imadu commented on controllers/users.js
> +async function hashPassword(password) {
Actually, this shouldn't be an async function. If I remember correctly, the `bcrypt.hash()` function doesn't return a promise, so it should be without the async/await keyword

2021-06-02 10:06 UTC, ebosetalee commented on .env
> +JWT="our_crypto_secret234"
my goodness i forgot

2021-06-02 10:06 UTC, ebosetalee commented on .env
> +JWT="our_crypto_secret234"
i need to reverse my commit

2021-06-02 10:20 UTC, ebosetalee commented on controllers/users.js
> +async function hashPassword(password) {
ok

2021-06-02 10:21 UTC, ebosetalee commented on controllers/login.js
> +        } else {
ok

2021-06-07 10:25 UTC, imadu approved these changes

2021-06-07 10:25 UTC, merged